# Generated by Django 5.0.4 on 2024-05-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('price', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
